# Generated by Django 5.2.8 on 2025-11-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('telegram_id', models.IntegerField(unique=True,
                                            verbose_name='ID в Telegram')),
                ('first_name', models.CharField(blank=True,
                                                max_length=100, null=True)),
                ('last_name', models.CharField(blank=True,
                                               max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100,
                                           null=True)),
                ('phone', models.CharField(blank=True, max_length=100,
                                           null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
