# Generated by Django 5.2.8 on 2025-12-01 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('event_date', models.DateField(verbose_name='День мероприятия')),
                ('started_at', models.TimeField(verbose_name='Время начала мероприятия')),
                ('ended_at', models.TimeField(verbose_name='Время окончания мероприятия')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField(verbose_name='ID ТГ')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('user_role', models.CharField(choices=[('organizer', 'Организатор'), ('guest', 'Гость'), ('speaker', 'Спикер')], default='guest', max_length=255, verbose_name='Роль пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='SpeakerTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, verbose_name='Тема доклада')),
                ('topic_date', models.DateField(verbose_name='День выступления')),
                ('started_at', models.TimeField(verbose_name='Время начала выступления')),
                ('ended_at', models.TimeField(verbose_name='Время окончания выступления')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetup_core.event', verbose_name='Мероприятие')),
                ('speaker', models.ForeignKey(limit_choices_to={'user_role': 'speaker'}, on_delete=django.db.models.deletion.CASCADE, to='meetup_core.user', verbose_name='Спикер')),
            ],
            options={
                'verbose_name': 'Тема спикера',
                'verbose_name_plural': 'Темы спикеров',
            },
        ),
        migrations.CreateModel(
            name='EventSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetup_core.event', verbose_name='Мероприятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetup_core.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка на мероприятие',
                'verbose_name_plural': 'Подписки на мероприятия',
                'unique_together': {('user', 'event')},
            },
        ),
    ]
