# Generated by Django 5.2.8 on 2025-12-01 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_core', '0002_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
